### PR TITLE
Update Svelte compiler version

### PR DESCRIPTION
**Pull request by StorytellerCZ**

### CODE REVIEW

**Comment by zodern** [comment]
Is `svelte:compiler` a dependency to only control the minimum svelte version used? Would it be possible to make it a weak dependency? This would allow apps that use `zodern:melte` to use the latest svelte version without being warned by `svelte:compiler` about using the wrong svelte version.

**Comment by StorytellerCZ** [comment]
@zodern feel free to submit improvements, I'm just doing the minimum advancement to have at least something asap.

**Comment by rdb** [comment]
I think we should rather make it a minimum version dependency rather than pinning it to a specific version.

**Comment by StorytellerCZ** [comment]
@rdb I agree, but I think that needs to happen in svelte:compiler. As I said before this is just a minimum advancement that allows for newer version of Svelte while the other improvement happens. Either way updating the compiler will have to happen.

**Comment by rdb** [comment]
Sorry for taking so long on this. I published a new version that accepts either version (to avoid the risk of this breaking anyone's application in a minor version).

**Pull request closed without merging**
